---
title: "Figures"
author: "Heterogeneity in direct replications in psychology and its association with effect size"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.asp = 1.3)
```

```{r load packages, data and source helper functions}
if(!require(readr)){install.packages("readr")}
if(!require(metafor)){install.packages("metafor")}
if(!require(dplyr)){install.packages("dplyr")}
if(!require(purrr)){install.packages("purrr")}
if(!require(ggplot2)){install.packages("ggplot2")}
if(!require(cowplot)){install.packages("cowplot")}
if(!require(boot)){install.packages("boot")}

library(readr) #To load data
library(dplyr) #For data transformation
library(purrr) #For data iteration
library(metafor) #To run meta-analyses
library(ggplot2) #Plot data
library(cowplot) #Combine several plots into one
library(boot) #Bootstrap confidence intervals for correlations

dat <- read_csv("../data/collated_summary_data.csv")

source("helper_functions_tables_figures.r") #Load functions to prep data for figures
```

```{r transform_df}
#Transform effect sizes to raw correlations
#'transform_MA' is a sourced function
res <- dat %>% 
  split(.$effect) %>%  #separate by effect, necessary step otherwise the function is applied overall
  map_dfr(transform_MA, .id = "effect") #apply function and transform back from list to dataframe

```

```{r MA_df}
summarizer <- function(x){
  fit <- rma(measure = "ZCOR", ri = x$r, ni = x$n, data = x) #takes raw correlation as input
  fitr <- rma(measure = "COR", ri = x$r, ni = x$n, data = x)
  data.frame(z = fit$b[[1]], I2 = fit$I2, H2trunc = fit$H2, H2 = fit$QE / (fit$k - 1),
             r = fitr$b[[1]], tau2r = fitr$I2) #estimates out
}
#Default method of metafor for calculating H2 is truncated at one. Alternative method for calculating H2 provides information also on excessive homogeneity, i.e, less variability than expected by chance (that is, does not have a lower limit of 1). This method approximates H2 as if we were using the Dersimonian and Laird estimate of tau2, although we use REML. See Higgins & Thompson, 2002 and ?print.rma.uni.

#Higgins, J., & Thompson, S. G. (2002). Quantifying heterogeneity in a meta-analysis. Statistics in medicine, 21(11), 1539-1558.
  
res2 <- res %>% 
  split(.$effect) %>%  #separate by effect, necessary step otherwise the function is applied overall
  map_dfr(summarizer, .id = "effect") %>% 
  mutate(z = abs(z), r = abs(r)) #Absolute values since we are interested in effect size rather than direction
```

```{r cor_het_effect_size, results = "hide", cache=TRUE}
#Basic correlations
cor.test(res2$I2, res2$z) #pearson I2

I2_fit <- summary(lm(I2 ~ z, data = res2)) #for annotating figures

cor.test(res2$tau2r, res2$r) #pearson tau2

tau2_fit <- summary(lm(tau2r ~ r, data = res2))

cor.test(res2$H2, res2$z) #pearson H2

H2_fit <- summary(lm(H2 ~ z, data = res2))

cor.test(res2$I2, res2$z, method = "spearman") #spearman

##Excluding anchoring effects
dropped_anchoring <- res2 %>%
  filter(!grepl("Anchoring", effect))

cor.test(dropped_anchoring$I2, dropped_anchoring$z) #pearson

#bootstrap confidence intervals
#code by Amir Abdol

#I2
pear <- function(formula, data, indices){ #pearson
     d <- data[indices,]
     fit <- cor.test(formula = ~ I2 + z, data=d)
     return(fit$estimate)
}

bootfit <- boot(data=res2, statistic=pear, R=1000, formula= ~ z + I2)

I2_ci_pears <- boot.ci(bootfit, type=c("perc", "bca")) #percentile and adjusted percental method (BCa)

spear <- function(formula, data, indices){ #spearman
     d <- data[indices,]
     fit <- cor.test(formula = ~ I2 + z, data=d, method = "spearman")
     return(fit$estimate)
}

options(warn=-1)
bootfit <- boot(data=res2, statistic=spear, R=1000, formula= ~ z + I2)
options(warn=0)

I2_ci_spear <- boot.ci(bootfit, type=c("perc", "bca"))

#Excluding anchoring effects
bootfit <- boot(data=dropped_anchoring, statistic=pear, R=1000, formula= ~ z + I2)

I2_dropped_ci_pears <- boot.ci(bootfit, type=c("perc", "bca")) #percentile and adjusted percental method (BCa)


#H2
pear <- function(formula, data, indices){
     d <- data[indices,]
     fit <- cor.test(formula = ~ H2 + z, data=d)
     return(fit$estimate)
}

bootfit <- boot(data=res2, statistic=pear, R=1000, formula= ~ z + H2)

H2_ci_pears <- boot.ci(bootfit, type=c("perc", "bca"))


```


```{r plot_res, cache = TRUE}

#Plots of H2 and I2 vs. fisher's z for all effects together

I2 <- ggplot(res2, aes(x = z, y = I2)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  coord_cartesian(ylim = c(0, 100)) +
  geom_text(x = 0.15, y = 80, fontface = "italic", size = 3.5, label = paste0("b = ", format(round(I2_fit$coefficients[2, 1], 2), nsmall = 2), ", r = ", format(round(sqrt(I2_fit$r.squared), 2), nsmall = 2))) +
  theme_classic() +
  scale_y_continuous(name = expression(paste(italic(I)^2," index"))) +
  scale_x_continuous(name = expression(paste("Effect size (Fisher's ", italic(z), ")")))

H2 <- ggplot(res2, aes(x = z, y = H2)) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  geom_text(x = 0.14, y = 5.9, size = 3.5, fontface = "italic", label = paste("b = ", format(round(H2_fit$coefficients[2, 1], 2), nsmall = 2), ", r = ", format(round(sqrt(H2_fit$r.squared), 2), nsmall = 2))) +
  theme_classic() +
  scale_y_continuous(name = expression(paste(italic(H)^2," index", sep = ""))) +
  scale_x_continuous(name = expression(paste("Effect size (Fisher's ", italic(z),")")))


effect_het <- plot_grid(I2, H2, nrow = 2, labels = c("a", "b"), align = "v") #combine plots
effect_het
#save_plot("../figures/effect-het.png", effect_het,
#          nrow = 2, base_height = 5, base_width = 5, dpi = 600)


```

```{r r_vs_tau2, fig.asp = 0.618, cache = TRUE}
r_tau2 <- ggplot(res2, aes(x = r, y = tau2r)) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  geom_text(x = 0.14, y = 75, size = 3.5, fontface = "italic", label = paste("b = ", format(round(tau2_fit$coefficients[2, 1], 2), nsmall = 2), ", r = ", format(round(sqrt(tau2_fit$r.squared), 2), nsmall = 2))) +
  theme_classic() +
  scale_y_continuous(name = expression(paste("Between studies variance ", italic(tau)^2))) +
  scale_x_continuous(name = expression(paste("Point-biserial correlation ", italic(r))))

r_tau2
# ggsave("../figures/r_tau2.png", dpi = 600, height =  4 , width = 6.47)

```

```{r corr_per_effect_type, cache = TRUE}
#Each set of input datapoints is meta-analyzed as per the original replication project
#Then correlated with tau2 per effect type
#Function 'est_heterogen_smd_raw' is sourced, see also tables.rmd
tau2_per_type <- dat %>% 
  split(.$effect) %>%  
  map_dfr(est_heterogen_smd_raw, .id = "effect")

tau2_per_type <- dat %>% #This is to add the effect_type names
  select(effect, effect_type) %>% 
  distinct() %>% 
  mutate(effect_type = recode(effect_type, 
                              d = "Standardized Mean Difference",
                              'Raw mean difference' = "Mean Difference",
                              'Risk difference' = "Risk Difference",
                              'r' = "Correlation")) %>% 
  left_join(tau2_per_type) %>% 
  mutate(eff_size = abs(eff_size)) #need the absolute values for plotting


fitter <- function(df){ #function to fit correlations for annotating facet plots
 fit <- summary(lm(tau2 ~ eff_size, data = df))
 data.frame(b = format(round(fit$coefficients[2, 1], digits = 2), nsmall = 2), #because map_dfr requires dataframe
            r = format(round(sqrt(fit$r.squared), digits = 2), nsmall = 2)) #output, the output is kept as two vars
}

labels <- tau2_per_type %>% 
  split(.$effect_type) %>% 
  map_dfr(fitter, .id = "effect_type") %>% 
  mutate(lab = paste0("b = ", b, ", r = ", r)) #put output into one variable for improved plotting
  

    

    
tau2_facet <- ggplot(tau2_per_type, aes(x = eff_size, y = tau2)) + 
  geom_point(alpha = 0.5) +
  geom_line(stat = "smooth", method = "lm", se = FALSE, color = "black", alpha = .5, linetype = "dashed") + #to set alpha for the line geom_line must be used rather than geom_smooth
  geom_text(data = labels, aes(label = lab), x = -Inf, y = Inf, hjust = -0.1, vjust = 6, size = 3.5, fontface = "italic") + #hjust and vjust can be used to annotate the same position in all facets
  scale_y_continuous(name = expression(paste("Between studies variance ", italic(tau)^2))) +
  scale_x_continuous(name = "Effect size") +
  theme_classic() +
  theme(strip.background = element_blank(), #remove box around titles
        strip.text = element_text(size = 12),
        panel.border = element_rect(fill = NA, colour = "black", #add box around plots
                                    size = 0.5, linetype = "solid")) + 
  facet_wrap(~effect_type, scales = "free") #use free scales since scales are different

tau2_facet
# ggsave("../figures/tau2_facet.png", dpi = 600, height =  7, width = 7)

```


```{r Plot_tau_against_I2, fig.asp = 0.618, cache = TRUE}
dat3 <- readRDS("../data/tau_simulation_results.RDS")
names(dat3) <- sort(unique(dat$effect)) #names were alphabetized upon splitting in simulation so must sort

OR2d <- c('Allowed vs. forbidden', 'Gain vs. loss framing', 'Norm of reciprocity', 'Low vs. high category scales') #effects that were transformed from OR to SMD

#Categorize effects by type of simulation for graphing
effect_type <- distinct(select(dat, effect, effect_type)) %>% 
  mutate(effect_type = ifelse(effect %in% OR2d | effect_type == "Risk difference" | 
                                effect_type == "Raw mean difference", "MD", effect_type),
         effect_type = recode(effect_type, "d" = 'SMD',
                              "r" = "Fisher's z"))



dat3 <- dat3 %>% 
  bind_rows(.id = "effect") %>% #create dataframe with identifier
  left_join(., effect_type) %>% 
  select(I2, tau, effect, effect_type) %>% 
  group_by(tau, effect, effect_type) %>% 
  summarize(I2 = mean(I2)) %>% #Take mean of I2 at each tau-level and for each effect
  ungroup()

#combined line plot gives good overview.
ggplot(dat3, aes(x = tau, y = I2, group = effect, color = effect_type)) +
  geom_line(alpha = 0.6) +
  theme_bw() +
  scale_x_continuous(name = expression(paste("Between studies standard deviation ", tau)),
                     minor_breaks = NULL) +
  scale_y_continuous(name = expression(paste(I^2," index", sep = "")),
                     minor_breaks = NULL) +
  coord_cartesian(ylim = c(0, 100)) +
  scale_color_brewer(name = "Effect type", palette = "Dark2", 
                     breaks = c("Fisher's z", "MD", "SMD")) +
  theme(legend.position = c(0.8, 0.4),
        legend.background = element_rect(linetype = "solid", color = "black")) +
  guides(color = guide_legend(override.aes = list(size = 1.4)))
  

# ggsave("../figures/tau-I2.png", dpi = 600, height =  4 , width = 6.47)

```


```{r Density_plot, fig.asp= 0.618, cache = TRUE}
dens <- readRDS("../data/power_simulation_results.RDS")
names(dens) <-  sort(unique(dat$effect))

#Simulated data at various heterogeneity levels, prep for plotting
I2_dist <- dens %>% 
  bind_rows(.id = "effect") %>% 
  rename(Heterogeneity = tau_index) %>% 
  mutate(Heterogeneity = recode(Heterogeneity,
                            '1' = "Zero",
                            '2' = "Small",
                            '3' = "Medium",
                            '4' = "Large"),
         Heterogeneity = as.factor(Heterogeneity))

#Observed I2 estimates, i.e, results from main table, see table.rmd
#Effects estimated with sourced function 'est_heterogeen_smd_raw'
observed <- dat %>% 
  split(.$effect) %>%  
  map_dfr(est_heterogen_smd_raw, .id = "effect") %>% 
  select(effect, I2 = s_I2) %>%
  mutate(Heterogeneity = "Observed")

ggplot(I2_dist, aes(x = I2, group = Heterogeneity, fill = Heterogeneity, linetype = Heterogeneity)) +
  geom_histogram(data = observed, aes(y = ..density.., x = I2), bins = 100, alpha = 1) +
  geom_density(alpha = 0.3) +
  theme_classic() +
  coord_cartesian(xlim = c(0, 100))  +
  scale_fill_brewer(palette = "Dark2",
                    breaks = c("Zero", "Small", "Medium", "Large", "Observed"),
                    labels = c("Zero (0%)", "Small (25%)", "Medium (50%)", "Large (75%)", "Observed")) +
  scale_linetype_manual(values = c( "dotdash", "dotted", "solid", "solid", "dashed"),
                        breaks = c("Zero", "Small", "Medium", "Large", "Observed"), 
                        labels = c("Zero (0%)", "Small (25%)", "Medium (50%)", "Large (75%)", "Observed")) +
  scale_color_brewer(palette = "Dark2", 
                     breaks = c("Zero", "Small", "Medium", "Large", "Observed"),
                     labels = c("Zero (0%)", "Small (25%)", "Medium (50%)", "Large (75%)", "Observed")) +
  theme(legend.position = c(0.85, 0.71),
        legend.background = element_rect(linetype = "solid", color = "black")) +
  scale_y_continuous(name = "Density") +
  scale_x_continuous(name = expression(paste(I^2," index", sep = ""))) +
  guides(fill = guide_legend(override.aes = list(alpha = c(rep(0.3, 4), 1))))

#ggsave("../figures/density-I2.pdf", dpi = 600, height =  4, width = 6.47, device = cairo_pdf())
```

