---
title: "Tables"
author: "Heterogeneity in direct replications in psychology and its association with effect size"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, miktex.verbose = TRUE)
```

```{r load packages, data and source functions}
if(!require(readr)){install.packages("readr")}
if(!require(metafor)){install.packages("metafor")}
if(!require(dplyr)){install.packages("dplyr")}
if(!require(purrr)){install.packages("purrr")}
if(!require(kableExtra)){install.packages("kableExtra")}

library(readr) #To load data
library(dplyr) #For data transformation
library(purrr) #For data iteration
library(metafor) #To run meta-analyses
library(kableExtra) #For creating good-looking pdf tables


dat <- read_csv("../data/collated_summary_data.csv")

source("helper_functions_tables_figures.r") #Load functions to prep data for figures
```

##Table 1
###Effect size $\rho_{xy}$ and its heterogeneity as a function of true effect size and measurement reliability.  
```{r effect-size-heterogeneity-table, cache = TRUE}
#library(kableExtra)
rooted_relabilities <- matrix(rep(c(.6, .7,.8), 3), ncol = 3)
rho <- c(0, .3, .5)
rel <- c("$\\sqrt{R_{xx'}}\\times\\sqrt{R_{yy'}}$ = .6", "$\\sqrt{R_{xx'}}\\times\\sqrt{R_{yy'}}$ = .7", "$\\sqrt{R_{xx'}}\\times\\sqrt{R_{yy'}}$ = .8")

rooted_relabilities <- sweep(rooted_relabilities, 2, rho, "*")
rooted_relabilities <- data.frame(rel, rooted_relabilities)

rooted_relabilities %>% knitr::kable("latex", booktabs = T, col.names = c("", "$\\rho_{xy}$ = 0", "$\\rho_{xy}$ = .3", "$\\rho_{xy}$ = .5"), escape = FALSE, digits = 2) %>% 
  kable_styling(position = "left") %>% 
  footnote(threeparttable = TRUE, escape = FALSE,
           general = "Values in cells are observed effect sizes arising from the true effect size $\\\\rho_{xy}$ and measurement reliabilites $\\\\sqrt{R_{xx'}}\\\\times\\\\sqrt{R_{yy'}}$. Code to reproduce table: osf.io/kf6pt/") %>% 
  row_spec(3, hline_after = T)

```


##Table 2
###Pre-registered multi-lab replication projects
```{r data-summary-table}
#library(dplyr)
#library(kableExtra)

#Shortened version of APA reference
papers <- c('Klein et al. (2014)', 
'Ebersole et al. (2016)',
'Alogna et al. (2014)',
'Alogna et al. (2014)',
'Eerland et al. (2016)',
'Hagger et al. (2016)',
'Cheung et al. (2016)',
'Wagenmakers et al. (2016)',
'Bouwmeester et al. (2017)',
"O'Donnell et al. (2017)")

##Full APA reference below
# c('Klein, R. A., Ratliff, K. A., Vianello, M., Adams, R. B., Jr., Bahn?k, S., Bernstein, M. J., . . . Nosek, B. A. (2014). Investigating variation in replicability: A "many labs" replication project. Social Psychology, 45(3), 142-152.', 
# 'Ebersole, C. R., Atherton, O. E., Belanger, A. L., Skulborstad, H. M., Allen, J. M., Banks, J. B., ... & Brown, E. R. (2016). Many Labs 3: Evaluating participant pool quality across the academic semester via replication. Journal of Experimental Social Psychology, 67, 68-82.',
# 'Alogna, V. K., Attaya, M. K., Aucoin, P., Bahn?k, S., Birch, S., Birt, A. R., ... & Buswell, K. (2014). Registered replication report: Schooler and engstler-schooler (1990). Perspectives on Psychological Science, 9(5), 556-578.',
# 'Alogna, V. K., Attaya, M. K., Aucoin, P., Bahn?k, S., Birch, S., Birt, A. R., ... & Buswell, K. (2014). Registered replication report: Schooler and engstler-schooler (1990). Perspectives on Psychological Science, 9(5), 556-578.',
# 'Eerland, A., Sherrill, A. M., Magliano, J. P., Zwaan, R. A., Arnal, J. D., Aucoin, P., ... & Crocker, C. (2016). Registered replication report: Hart & Albarrac?n (2011). Perspectives on Psychological Science, 11(1), 158-171.',
# 'Hagger, M. S., Chatzisarantis, N. L., Alberts, H., Anggono, C. O., Batailler, C., Birt, A. R., ... & Calvillo, D. P. (2016). A multilab preregistered replication of the ego-depletion effect. Perspectives on Psychological Science, 11(4), 546-573.',
# 'Cheung, I., Campbell, L., LeBel, E. P., Ackerman, R. A., Aykutoglu, B., Bahn?k, S., ... & Carcedo, R. J. (2016). Registered Replication Report: Study 1 from Finkel, Rusbult, Kumashiro, & Hannon (2002). Perspectives on Psychological Science, 11(5), 750-764.',
# 'Wagenmakers, E. J., Beek, T., Dijkhoff, L., Gronau, Q. F., Acosta, A., Adams Jr, R. B., ... & Bulnes, L. C. (2016). Registered Replication Report: Strack, Martin, & Stepper (1988). Perspectives on Psychological Science, 11(6), 917-928.',
# 'Bouwmeester, S., Verkoeijen, P. P., Aczel, B., Barbosa, F., B?gue, L., Bra?as-Garza, P., ... & Evans, A. M. (2017). Registered Replication Report: Rand, Greene, and Nowak (2012). Perspectives on Psychological Science, 12(3), 527-542.',
# "O'Donnell, M., Nelson, L., McLatchie, N. M., & Lynott, D. J. (2017). Registered Replication Report: Dijksterhuis & van Knippenberg (1998): Multilab direct replication of: A variant of study 4 from Dijksterhuis, A., & van Knippenberg, A.(1998). The relation between perception and behavior, or how to win a game of trivial pursuit. Journal of personality and social psychology. Perspectives on Psychological Science."

description <- c("Two correlational effects: 'Gender math attitude' compared implicit attitudes (IAT) towards math between genders and 'IAT correlation math' correlated implicit attitudes with self-reported measures. The remainder were experiments with two independent groups. The groups were primed in some way (Anchoring 1-4; low vs. high category scales; norm of reciprocity; flag priming; currency priming), asked to imagine slightly different situations (Sunk costs; gain vs. loss framing; gambler's fallacy; imagined contact) or asked their agreement with statements presented differently (Allowed vs. forbidden; quote attribution). ", #ML1
            "Several effects were experiments with two independent groups. The groups were either primed in some way (Power and perspective; warmth perceptions; subjective distance interaction), saw slightly different statements (Elaboration likelihood interaction; credentials interaction) or experienced different situations (weight embodiment). Examined interactions were between treatment conditions and participant characteristics. One priming effect (metaphor) compared two treatment groups with a control. One effect was correlational: 'persistence and conscientiousness' was measured by an unsolvable anagram task and self-report respectively. The Stroop task is a within-person experiment with two conditions and the 'Availability' effect asks participants to judge whether some letters are more common in the first or third position.", #ML2
                 "Verbal overshadowing 1; Independent two-group experiment. Participants either described a robber after watching a video or listed countries/capitals and after a filler task attempted to identify the robber in a lineup.", #RRR1
            "Verbal overshadowing 2; Different from 1 only in that the filler task took place before the descriptive task instead of after.", #RRR2
                 "Grammar on intentionality/intention attribution/detailed processing; Independent two-group experiment with three outcome variables. Actions either described in imperfect or perfect.", #RRR3
            "Ego depletion; Independent two-group experiment. Participants either assigned to a cognitively demanding task or a neutral, and performance was then measured in a subsequent cognitive task.", #RRR4
            "Commitment on neglect/exit; Independent two-group experiment with two outcome variables. Participants either primed to think about commitment to or independence from partner.", #RRR5
            "Facial feedback hypothesis; Independent two-group experiment. Participants either induced to 'smile' or 'pouth' with a pen and then rated funniness of cartoons. ", #RRR6
            "Intuitive cooperation; Independent two-group experiment. Economic game with money contribution to a common pool either under time pressure or time delay.",
                 "Professor priming; Independent two-group experiment. Participants primed with either a 'professor' or 'hooligan' stimuli. Outcome was percentage correct trivia answers.") #RRR8


US_online <- dat %>% #Extract the (max when multiple effects) number of US/online labs per RP
  group_by(rp, effect) %>% 
  summarize(US = sum(country == "USA"),
            online = sum(in_lab == 0)) %>% 
  group_by(rp) %>% 
  summarize(US = max(US),
            online = max(online)) %>% 
  ungroup() %>% select(US, online)

sample_settings <- c("26/36 samples were primarily university students, 3 general population and 7 undescribed. 9/36 samples were online, including all the general population ones.", #https://osf.io/g3udn/, ML1
                     "20/21 samples were university students, 1 general population which was also the only online sample.", #Ml3
                     "31/32 samples were undergraduate students between 18-25, 1 general population which was also the only online sample.", #RRR1
                     "22/23 samples were undergraduate students between 18-25, 1 general population which was also the only online sample.", #RRR2
                     "11/12 samples were undergraduate students mostly between 18-25, one of which was online. 1 sample was a broader online sample.", #RRR3
                     "All samples consisted of in-lab undergraduate students", #RRR4
                     "All samples consisted of in-lab undergraduate students between 18-25", #RRR5
               "All but one sample explicitly consisted of students and all took place in-lab. The last sample was recruited at university grounds.", #RRR6
               'All samples consisted of in-lab undergraduate students between 18-34.', #RRR7
                     "All samples consisted of in-lab undergraduate students betweeb 18-25") #RRR8

#1) what kind of samples

summary.table <- dat %>% 
  group_by(rp) %>% 
  summarize(Countries = n_distinct(country),
            k = n_distinct(Site), 
            Effects = n_distinct(effect),
            Participants = if(Effects == 1){sum(Ntotal)}
                           else{sum(Ntotal) / Effects}) %>% #average across effects
  mutate(Paper = papers,
         'Sample and Settings' = sample_settings,
         'Description of Effects' = description,
         'K (US)' = paste0(k, " (", US_online$US, ")")) %>% 
  select(RP = rp, Paper, Countries,'K (US)', everything(), -k) #change order of columns

summary.table %>% knitr::kable("latex", 
                               booktabs = TRUE,
                               digits = 0) %>% 
  kable_styling("repeat_header", font_size = 7) %>% 
  column_spec(2, width = "7em") %>% #specify width of paper column 
  column_spec(7, width = "16em") %>% 
  column_spec(8, width = "30em") %>% 
  footnote(threeparttable = TRUE,
           general = "For studies with several effects the number of participants is the average across effects, rounded to the closest whole number. Participant numbers are those used for primary analyses by original authors (i.e., after exclusions). RP = Replication Project, K (US) = no. primary studies (number of US studies), ML = Many Labs, RRR = Registered Replication Report. Code to reproduce table: osf.io/kf6pt/") %>% 
  landscape()
```

```{r prep-heterogeneity-table, cache = TRUE}
#library(metafor)
#library(dplyr)
#library(purrr)

#fit a random effects model to all empirical data
#Each set of input datapoints is meta-analyzed as per the original replication project
#Function 'est_heterogen_smd_raw' is sourced
res <- dat %>% 
  split(.$effect) %>%  #separate by effect, necessary step otherwise the function is applied overall
  map_dfr(est_heterogen_smd_raw, .id = "effect") #apply function, rbind results into dataframe ('dfr'), make sure purrr is up to date

#Transform effect sizes to raw correlations
#'transform_MA' is a sourced function
dat2 <- dat %>% 
  split(.$effect) %>%  #separate by effect, necessary step otherwise the function is applied overall
  map_dfr(transform_MA, .id = "effect") #apply function and transform back from list to dataframe

summarizer <- function(x){ #function to run rma on transformed biserial and correlations
  fitr <- rma(yi = x$r, vi = x$vi, data = x) #rma for biserial and pearson correlations (distinct per effect!)
  ci <- confint(fitr)$random[c(1, 3), ]
  data.frame(r = fitr$b[[1]], tau2 = fitr$tau2, tau2.lb = ci[1, 2], tau2.ub = ci[1, 3],
             I2 = fitr$I2, I2.lb = ci[2, 2], I2.ub = ci[2, 3]) 
}

#estimate tau2 for tranformed biserial and pearson's correlations
res2 <- dat2 %>% 
  split(.$effect) %>%  #separate by effect, necessary step otherwise the function is applied overall
  map_dfr(summarizer, .id = "effect")

#NB! note that for low vs. high category scales, the I2 lower bound is zero, but after transformation
#the tau2 lower bound is *not* zero. This is an indication of the problems with effect size tranformations.

res <- res %>%
  mutate(tau2 = res2$tau2, #For table 3, report tau2 and transformed effect sizes (biserial correlations)
         tau2_ci.lb = res2$tau2.lb,
         tau2_ci.ub = res2$tau2.ub,
         r = res2$r)

#Add rp and k to the data-frame and prep for table
het <- dat %>% 
  select(rp, Site, effect, effect_type) %>% 
  group_by(rp, effect) %>% 
  summarize(effect_type = unique(effect_type),
            k = n_distinct(Site)) %>% 
  left_join(res) %>% 
  mutate(effect_type = recode(effect_type, 
                              d = "SMD.",
                              'Raw mean difference' = "MD",
                              'Risk difference' = "RD")) %>% 
  ungroup()

#Load simulation results (power/type 1 error for all effects)
dens <- readRDS("../data/power_simulation_results.RDS")
names(dens) <-  sort(unique(dat$effect)) #names were alphabetized upon splitting in simulation so must sort

#Summary of simulation results, needs to be combined with main part of table
I2_power <- dens %>% 
  bind_rows(.id = "effect") %>% 
  group_by(effect, tau_index) %>% 
  summarize(power = mean(Qp <= 0.05)) %>% #Estimate power/type 1 error for each tau level and effect
  ungroup() %>% 
  tidyr::spread(key = tau_index, value = power) %>% #prep for table
  rename(zero = '1', small = '2', medium = '3', large = '4')

#Combine dataframes to create full table
het <-  het %>% 
  left_join(I2_power) %>% 
  arrange(desc(s_I2),  desc(s_ci.ub)) %>% #sort by tau2 and upper CI bound
  mutate(I2_ci = paste0("[", trimws(format(round(s_ci.lb, 2), nsmall = 2)), ", ", trimws(format(round(s_ci.ub, 2), nsmall = 2)), "]"), #Round and put confidence interval between brackets, e.g., [0, 0.41]
         tau2_ci = paste0("[", trimws(format(round(tau2_ci.lb, 2), nsmall = 2)), ", ", trimws(format(round(tau2_ci.ub, 2), nsmall = 2)), "]")) %>% 
  select(rp, effect, k, effect_type, eff_size, s_I2, I2_ci, r, tau2, tau2_ci, zero, small, medium, large)

```

##Table 3
###Heterogeneity across primary effects and statistical power of ten multi-lab replication projects, ordered with respect to estimated between studies variance ($\tau^2$).
```{r heterogeneity-table, cache = TRUE}
#library(kableExtra)

het %>% knitr::kable("latex", align = "c", booktabs = TRUE, escape = FALSE, digits = 2, col.names = c("RP", "Effect", "K", "Effect type", "Effect size estimate",  "$I^2$(\\%)", "$I^2$ 95\\% CI", "r*" , "$\\tau^2$", "$\\tau^2$ 95\\% CI", "Zero", "Small", "Medium", "Large")) %>% 
  add_header_above(c(" " = 10, "Level of heterogeneity" = 4)) %>% 
  add_header_above(c(" " = 10, "Type I Error Rate & Statistical Power" = 4)) %>% 
  kable_styling("scale_down", font_size = 7) %>%
  column_spec(5, width = "5em") %>% #make sure the 'Effect size estimate' header is wrapped 
  footnote(threeparttable = TRUE, escape = FALSE,
           general = "Effects were estimated in metafor using REML. The following effects are odds ratios transformed into standardized mean differences: 'Allowed vs. forbidden', 'Gain vs. loss framing', 'Norm of reciprocity', 'Low vs. high category scales'. RP = Replication Project, k = no. primary studies, CI = confidence intervals, r* = effect sizes as correlations and biserial correlations. Statistical power and type I error rates were simulated, where Zero = simulated type 1 error, and the other headers represent simulated power under small/medium/large heterogeneity ($I^2$ = 25/50/75\\\\%) respectively. SMD = Standardized Mean difference (Hedge's g), MD = Mean Difference, RD = Risk Difference, r = correlation. Code to reproduce table: osf.io/kf6pt/",
           alphabet = "These effects were simulated as standardized mean differences") %>% 
  landscape()


```


